Repository AvinashMahala/SE1_Project, pull requests merged in 2023-10, with the labels that each got.

#30 Admin area
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codecrafters/quizquest/activities/AdminDashboardActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/CommonLoginRegistrationActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/admin/AnalyticsActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/admin/CategoryManagementActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/admin/QuestionManagementActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/admin/UserAccountManagementActivity.java
  app/src/main/java/com/codecrafters/quizquest/adapters/AdminQuizCategoryAdapter.java
  app/src/main/java/com/codecrafters/quizquest/models/AdminQuizCategory.java
  app/src/main/res/drawable/rounded_button.xml
  app/src/main/res/layout/activity_admin_dashboard.xml
  app/src/main/res/layout/activity_analytics.xml
  app/src/main/res/layout/activity_category_management.xml
  app/src/main/res/layout/activity_common_login_registration.xml
  app/src/main/res/layout/activity_question_management.xml
  app/src/main/res/layout/activity_user_account_management.xml
  app/src/main/res/layout/item_quiz_category.xml
Labels: enhancement, code refactoring, backend, database related

#31 Implemented user profile and admin login
  app/src/main/java/com/codecrafters/quizquest/activities/CommonLoginRegistrationActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/RegistrationActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/UserDashboardActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/UserProfileActivity.java
  app/src/main/res/layout/activity_common_login_registration.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/layout/activity_user_dashboard.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, backend, database related

#32 Added firebase code for getting data form DB and a new page for…
  .gitignore
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codecrafters/quizquest/activities/QuizCategoriesActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/QuizDashboardActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/RecyclerViewInterface.java
  app/src/main/java/com/codecrafters/quizquest/adapters/QuizCategoryAdapter.java
  app/src/main/java/com/codecrafters/quizquest/models/QuizCategory.java
  app/src/main/res/layout/activity_quiz_dashboard2.xml
Labels: enhancement, backend, database related

#33 User Dashboard
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codecrafters/quizquest/activities/CommonLoginRegistrationActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/UserProfileDashboardActivity.java
  app/src/main/java/com/codecrafters/quizquest/adapters/QuizHistoryAdapter.java
  app/src/main/java/com/codecrafters/quizquest/models/QuizCategory.java
  app/src/main/java/com/codecrafters/quizquest/models/QuizHistoryItem.java
  app/src/main/java/com/codecrafters/quizquest/models/User.java
  app/src/main/java/com/codecrafters/quizquest/repositories/UserDataRepository.java
  app/src/main/java/com/codecrafters/quizquest/viewmodels/UserProfileDashboardViewModel.java
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/layout/activity_user_profile_dashboard.xml
  app/src/main/res/layout/quiz_history_item.xml
  app/src/main/res/values/colors.xml
Labels: enhancement, backend

#35 New changes
  app/src/main/java/com/codecrafters/quizquest/activities/CommonLoginRegistrationActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/RegistrationActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/admin/CategoryClickListener.java
  app/src/main/java/com/codecrafters/quizquest/activities/admin/CategoryManagementActivity.java
  app/src/main/java/com/codecrafters/quizquest/adapters/AdminQuizCategoryAdapter.java
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/layout/activity_category_management.xml
  app/src/main/res/layout/activity_common_login_registration.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/layout/item_quiz_category.xml
  gradle.properties
Labels: enhancement, code refactoring, backend, database related

#36 Admin categories edit
  app/src/main/java/com/codecrafters/quizquest/activities/admin/CategoryManagementActivity.java
  app/src/main/res/drawable/dialog_border.xml
  app/src/main/res/drawable/header_background.xml
  app/src/main/res/layout/activity_category_management.xml
  app/src/main/res/layout/edit_category_dialog.xml
Labels: enhancement, code refactoring, backend, database related

#40 splash screen
  app/src/main/res/animator/logo_animation.xml
  app/src/main/res/animator/text_animation.xml
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/drawable/edittext_background.xml
  app/src/main/res/drawable/gradient_background.xml
  app/src/main/res/drawable/quizquestlogo.png
  app/src/main/res/font/pacifico.ttf
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/values/strings.xml
Labels: ui

#41 Implement Quiz taking page and change DB tables
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codecrafters/quizquest/activities/QuizCategoriesActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/QuizDashboardActivity.java
  app/src/main/java/com/codecrafters/quizquest/activities/QuizQuestionActivity.java
  app/src/main/res/layout/activity_quiz_question.xml
Labels: enhancement, backend
